### ISSUE TITLE
onContentLoaded never set in har

### ISSUE THREAD

**Issue by pierredelacelle** [webmetrics/browsermob-proxy#30]
I'm using browsermob proxy through the REST API.

I noticed that onContentLoaded is never set in the har that we get from browsermob. 

I read the source code as well and i didn't see anything about setting it in the har. 

There is setters and accessors for onContentLoad but I can't see when they are (or have to be) triggered.

**Comment by lightbody** [comment]
I don't think BrowserMob Proxy will ever provide this. The reason is that it requires knowledge inside the browser, which BMP doesn't really have access to. What I recommend is if you want more complete timings, you should execute some JavaScript to fetch the [Navigation Timing](https://developer.mozilla.org/en-US/docs/Navigation_timing) information and then sprinkle in that data in to the HAR returned by the proxy.

Sorry I don't have a better answer, and sorry it took me a year to respond!
