### ISSUE TITLE
BrowserMob Proxy extremely slow when recording HAR file

### ISSUE THREAD

**Issue by DigitalGoldfish** [webmetrics/browsermob-proxy#66]
Whenever i enabled HAR File Recording all pages requested through the proxy started to load very slow. I traced the problem back to the BrowserMobHttpClient (line 411).

<code>UserAgentInfo uai = p.parse(userAgent);</code>

This took about 5 seconds for each request, and then throwing an IOException. 

I don't know if this is relevant but I have to use an upstream proxy to access the internet. The problem happened with all pages I tried (e.g. google.com, facebook.com, ...) both if i use the proxy via the REST API or start it from Java directly (in a selenium test). As I didn't need the browser I just removed the parsing of the UA string and it works fine and speedy again.

**Comment by volodymyr-mykhailyk** [comment]
I've encountered the same issue when I removed 2 files from temp folder. They was somehow related to cache of the UA parsing procedures.

**Comment by volodymyr-mykhailyk** [comment]
Ok. I've managed to track this issue.
If temp folder doesn't have userAgentString.properties file

It assume cache need to be updated. In this case it tries to download results from:
`http://user-agent-string.info/rpc/get_data.php?key=free&format=ini`
and check version from:
`http://user-agent-string.info/rpc/get_data.php?key=free&format=ini&ver=y`

It looks like sometimes this server is down. which causes long replies. And it looks like data cannot be downloaded - it is requested on every request.

Workaround:
create `userAgentString.properties` file in temp folder with following content:
    lastUpdateCheck=200000000000000
    currentVersion=1

This will prevent cache to be updated.

and create file `userAgentString.txt` with empty content. 

Such actions will produce lot of exceptions in console. but at least it will be working.

To my humble opinion this code of UA parsing is piece of crap. I spent whole day trying to understand why proxy stopped working. And found that cause is piles of unmaintainable unstable and unreliable code :(

**Comment by roydekleijn** [comment]
How does it work if I use browsermob in a grid setup ?
Browsermob proxy is running on the HUB. (ubuntu machine)

Where should I put those files? on the hub or the nodes?

and which temp folder? just c:\temp  ?

Thanks,
Roy

**Comment by ASavka** [comment]
If you're running tests on Ubuntu OS, put those files into   /tmp
It solved my problem.

Thanks Volodymyr!

**Comment by roydekleijn** [comment]
ok, can you explain me how to do that?

**Comment by lightbody** [comment]
Todd's patch removes the User-Agent parsing entirely, but I'm not sure we need to go that extreme (though I can be convinced!). Instead, I just committed some code that should help speed things up and give you more control over how long the cache sticks around: https://github.com/webmetrics/browsermob-proxy/commit/718fa15cc28667a2c0e468ed2a562e22084ed060 and https://github.com/webmetrics/browsermob-proxy/commit/5e06bffc4419f8af9018578109b82f40b89aae63

The quick answer is:
- If you're running via command line, you can do -uaCache to control the # of days to keep the UA database around. It defaults to 1 day, but you can do a very large number to prevent this issue.
- If you're running as an embedded Java program, you can call this code:

``` java
((OnlineUpdateUASparser) BrowserMobHttpClient.PARSER).setUpdateInterval(...);
```

Going to close this out as "resolved" but happy to discuss more on the mailing list.

**Comment by vanslly** [comment]
To clarify for anyone reading this issue because one day their BrowserMob proxy started to experience terrible performance when collecting an HAR. BrowserMob as said above makes a request to the "http://user-agent-string.info" website to download the latest version of the user-agent database, and when this website goes down, then the user-agent database cannot be downloaded and you experience the timeout issues detailed here.

If you have used the BrowserMob proxy before and ran a HAR trace before then chances are you have a userAgentString.txt (the user-agent database) and a userAgentString.properties file (cache information for the user-agent database) in your temp directory. On Windows that meant %TEMP% (you're user profile temp directory. Ex: C:\Users\{username}\AppData\Local\Temp).

If you find both files in your temp directory then edit the cache information file as detailed above with:
lastUpdateCheck=200000000000000
currentVersion=1

That will ensure the BrowserMob proxy will not try downloading the user-agent database even if the cache information file indicates it might be a bit stale. This step resolved the issue for me.

This is a remedial solution, and it would be nice if this database can be stored locally to the BrowserMob runner and configured to use it (perhaps configuring the Java temp directory using command line arguments).

**Comment by lightbody** [comment]
Thanks for the reminder. I hope to eventually remove this dependency and have an issue to remind me here:

https://github.com/lightbody/browsermob-proxy/issues/9

**Comment by danishS** [comment]
Is there a workaround for Mac? 

Found a way to update the temp folder with the files in Mac. 
Open Terminal and type the following command and hit enter
  printenv | sort 
Look for the value for TMPDIR
Paste the files userAgentString.txt and userAgentString.properties in the folder, and you should be good to go!
